- build.gradle
- src/main/java/fouragrant/scentasy/biz/member/domain/DayAndNight.java
- src/main/java/fouragrant/scentasy/biz/member/domain/Gender.java
- src/main/java/fouragrant/scentasy/biz/member/domain/Member.java
- src/main/java/fouragrant/scentasy/biz/member/domain/Season.java
- src/main/java/fouragrant/scentasy/biz/member/domain/extraInfo.java
- src/main/java/fouragrant/scentasy/biz/perfume/domain/Perfume.java
- src/main/java/fouragrant/scentasy/biz/post/domain/Post.java
- src/main/java/fouragrant/scentasy/common/dto/BaseTimeEntity.java
- src/main/java/fouragrant/scentasy/config/SwaggerConfig.java
- src/main/resources/application-dev.yml
- src/main/resources/application-local.yml
- src/main/resources/application.properties
- src/main/resources/application.yml
- domain setting
- swagger setting
- yml setting
> project init

- src/main/java/fouragrant/scentasy/config/SecurityConfig.java
- src/main/java/fouragrant/scentasy/config/SwaggerConfig.java
- src/main/resources/application-dev.yml
- src/main/resources/application.yml
- src/test/java/fouragrant/scentasy/ScentasyApplicationTests.java
관련 이슈
- #9 
- 서버 배포 관련 리팩토링 작업을 했습니다.
-  application.yml에서 dev로 수정
- securityConfig에 스웨거 주소 추가
- 스웨거 설정 파일에 서버 주소 추가
> 🔨 Refactor: #9 refactor for deploy

- src/main/java/fouragrant/scentasy/config/CorsConfig.java
관련 이슈
- #12  
- cors 관련 에러 해결을 위해 CorsConfig 파일 수정
주요 변경 사항이나 추가된 기능에 대해 설명해주세요. 
- config.addAllowedOrigin("http://localhost:3000");
- source.registerCorsConfiguration("/**", config);
> fix: cors 관련 corsConfig파일 수정

- src/main/java/fouragrant/scentasy/biz/member/cotroller/ExtraInfoController.java
- src/main/java/fouragrant/scentasy/biz/member/domain/Member.java
- src/main/java/fouragrant/scentasy/biz/member/domain/MemberStatus.java
- src/main/java/fouragrant/scentasy/biz/member/dto/ExtraInfoResDto.java
- src/main/java/fouragrant/scentasy/biz/member/service/AuthService.java
- src/main/java/fouragrant/scentasy/biz/member/service/ExtraInfoService.java
- src/main/java/fouragrant/scentasy/common/exception/ErrorCode.java
관련 이슈
- #11 
- 추가정보에 대한 예외처리 및 응답형식을 수정했습니다.
- 에러코드 추가
- 닉네임 중복, 인증 오류 예외처리 추가
- 추가정보 응답 데이터 닉네임, 멤버 이미지 URL로 형식 수정
> 🔨 Refactor: #11 추가정보 예외처리 및 응답형식 수정

- src/main/java/fouragrant/scentasy/biz/chat/controller/ChatController.java
- src/main/java/fouragrant/scentasy/biz/chat/domain/Chat.java
- src/main/java/fouragrant/scentasy/biz/chat/dto/ChatReqDto.java
- src/main/java/fouragrant/scentasy/biz/chat/dto/ChatResDto.java
- src/main/java/fouragrant/scentasy/biz/chat/repository/ChatRepository.java
- src/main/java/fouragrant/scentasy/biz/chat/service/ChatService.java
- src/main/java/fouragrant/scentasy/biz/member/CustomUserDetails.java
- src/main/java/fouragrant/scentasy/biz/member/domain/ExtraInfo.java
- src/main/java/fouragrant/scentasy/biz/member/domain/Member.java
- src/main/java/fouragrant/scentasy/biz/member/service/CustomUserDetailsService.java
- src/main/java/fouragrant/scentasy/config/SecurityConfig.java
- src/main/resources/application-dev.yml
- src/main/resources/application-local.yml
- src/main/resources/application.yml
관련 이슈
- 채팅 기능 임시 구현
- 채팅 기능을 임시로 구현했습니다.
- extraInfo id 형식 변경
> ✨ Feature: #7 feature chat

- src/main/java/fouragrant/scentasy/biz/chat/controller/ChatController.java
- src/main/java/fouragrant/scentasy/biz/chat/dto/ChatListResDto.java
- src/main/java/fouragrant/scentasy/biz/chat/repository/ChatRepository.java
- src/main/java/fouragrant/scentasy/biz/chat/service/ChatService.java
관련 이슈
- #7 
- 채팅 관련 기능을 추가적으로 구현했습니다
- 멤버별 채팅 내역 날짜를 조회할 수 있습니다.
- 멤버별 해당 날짜에 대한 채팅 내역을 조회할 수 있습니다. 
- 스웨거 참고
> ✨ Feature: #7 feature chat retrieve

- src/main/java/fouragrant/scentasy/biz/member/cotroller/AuthController.java
- src/main/java/fouragrant/scentasy/biz/member/cotroller/ExtraInfoController.java
관련 이슈
- #20 
- 스웨거 작업을 했습니다
- auth 관련 스웨거 작성사항 수정
- extraInfo 관련 스웨거 작성사항 수정
> 🔨 Refactor: #20 swagger setting for auth

- src/main/java/fouragrant/scentasy/biz/chat/dto/ChatReqDto.java
- src/main/java/fouragrant/scentasy/biz/chat/service/ChatService.java
- src/main/java/fouragrant/scentasy/biz/member/domain/ExtraInfo.java
- src/main/java/fouragrant/scentasy/biz/member/domain/Member.java
- src/main/java/fouragrant/scentasy/biz/member/service/ExtraInfoService.java
관련 이슈
- #7 
- 사용자가 채팅 시 본인의 추가정보도 전송할 수 있도록 수정했습니다
> ✨ Feature: #7 feature chat with extra info

- src/main/java/fouragrant/scentasy/biz/member/service/AuthService.java
관련 이슈
- #30 
- 추가정보가 없는 회원이 로그인 시 에러코드를 사용하여 응답 처리하였습니다.
- 로그인 시 추가정보가 있는지 확인
- 없을 시 적절한 에러코드와 응답을 반환
> 🔨 fix: 로그인 시 응답 에러 해결

- src/main/java/fouragrant/scentasy/config/CorsConfig.java
관련 이슈
- #20 
- 스웨거 관련 cors 처리해줬습니다.
> 🔨 fix: 스웨거 cors 해결

- src/main/java/fouragrant/scentasy/config/CorsConfig.java
관련 이슈
- #20 
- SwaggerConfig 수정
> 🔨 fix: 스웨거 cors 해결2

- src/main/java/fouragrant/scentasy/biz/member/cotroller/ExtraInfoController.java
- src/main/java/fouragrant/scentasy/biz/member/repository/ExtraInfoRepository.java
- src/main/java/fouragrant/scentasy/biz/member/service/ExtraInfoService.java
- src/main/java/fouragrant/scentasy/biz/member/service/MemberService.java
- src/main/java/fouragrant/scentasy/common/exception/ErrorCode.java
관련 이슈
- #11 
- 추가정보 중복 입력 오류 예외처리 추가
- 추가정보 수정 기능 추가
- 이미 추가정보를 입력한 회원이 또 입력 요청을 보낼 시 예외처리를 추가했습니다.
- 나중에 추가정보를 수정할 수 있도록 추가정보 수정 기능을 추가했습니다.
> ✨ Feature: #11 추가정보 수정 기능 구현

- src/main/java/fouragrant/scentasy/biz/post/controller/CommentController.java
- src/main/java/fouragrant/scentasy/biz/post/controller/PostController.java
- src/main/java/fouragrant/scentasy/biz/post/domain/Comment.java
- src/main/java/fouragrant/scentasy/biz/post/domain/Post.java
- src/main/java/fouragrant/scentasy/biz/post/domain/PostLike.java
- src/main/java/fouragrant/scentasy/biz/post/dto/CommentListResDto.java
- src/main/java/fouragrant/scentasy/biz/post/dto/CommentReqDto.java
- src/main/java/fouragrant/scentasy/biz/post/dto/CommentResDto.java
- src/main/java/fouragrant/scentasy/biz/post/dto/PostReqDto.java
- src/main/java/fouragrant/scentasy/biz/post/dto/PostResDto.java
- src/main/java/fouragrant/scentasy/biz/post/mapper/CommentMapper.java
- src/main/java/fouragrant/scentasy/biz/post/mapper/PostMapper.java
- src/main/java/fouragrant/scentasy/biz/post/repository/CommentRepository.java
- src/main/java/fouragrant/scentasy/biz/post/repository/PostLikeRepository.java
- src/main/java/fouragrant/scentasy/biz/post/repository/PostRepository.java
- src/main/java/fouragrant/scentasy/biz/post/service/CommentService.java
- src/main/java/fouragrant/scentasy/biz/post/service/PostService.java
- src/main/java/fouragrant/scentasy/common/Response.java
- src/main/java/fouragrant/scentasy/common/exception/ErrorCode.java
- src/main/resources/application.yml
관련 이슈
- 
- 커뮤니티 개발을 진행하였습니다.
- 전체 포스트를 불러오는 API
- 인기있는 포스트 3개 가져오는 API
- 커뮤니티 글 작성
-  커뮤니티 글 조회
- 커뮤니티 글 삭제
- 커뮤니티 글 수정
- 커뮤니티 댓글 작성
- 커뮤니티 대댓글 작성
- 커뮤니티 댓글 조회
- 커뮤니티 댓글 수정
- 커뮤니티 댓글 삭제
- 커뮤니티 좋아요 기능
- 커뮤니티 조회수 기능
- 사용자 포스트 조회
- 사용자가 좋아요 누른 포스트 조회
- 현재 인기 있는 포스트 세 개 보여주기 기능
- 최신 글 목록 가져오기
- 
-
> Feature/#37 community-포스트 전체 조회 및 인기있는 포스트 조회

- src/main/java/fouragrant/scentasy/biz/post/controller/CommentController.java
- src/main/java/fouragrant/scentasy/biz/post/controller/PostController.java
관련 이슈
- 커뮤니티에서 swagger 관련 버그를 수정했습니다
- 커뮤니티 controller에서 swagger 스키마 수정했습니다
- 
- 
-
> Bug/커뮤니티 swagger 관련 버그 수정

- src/main/java/fouragrant/scentasy/biz/perfume/controller/PerfumeController.java
- src/main/java/fouragrant/scentasy/biz/perfume/repository/PerfumeRepository.java
- src/main/java/fouragrant/scentasy/biz/perfume/service/PerfumeService.java
관련 이슈
- #35 
- 추가로 필요한 API 구현과 리팩토링 진행했습니다.
- 특정 멤버의 전체 향수 개수 조회 기능
- 향수 목록 반환 List<Perfume> 형태로 변경
- 향수 관련 API 경로 통일성 부여
> ✨ Feature: #35 향수 개수 조회 기능 구현 및 리팩토링

- src/main/java/fouragrant/scentasy/biz/post/controller/PostController.java
- src/main/java/fouragrant/scentasy/biz/post/domain/Post.java
- src/main/resources/application.yml
관련 이슈
- 커뮤니티 포스트 삭제 의존성 오류
- 커뮤니티 포스트 삭제 의존성 오류 수정 
- 커뮤니티 좋아요 삭제 리턴 값 변경
- 
- 
-
> 🐛Bug: #43 community 오류 수정

- src/main/java/fouragrant/scentasy/biz/member/domain/Scent.java
- src/main/java/fouragrant/scentasy/biz/perfume/controller/PerfumeController.java
- src/main/java/fouragrant/scentasy/biz/perfume/dto/PerfumeNotesDto.java
- src/main/java/fouragrant/scentasy/biz/perfume/service/PerfumeService.java
관련 이슈
- Perfume 플라스크 연결 및 레시피 스트링으로 변경
- Perfume과 플라스크를 연결합니다.
- 플라스크에서 받아온 0,1 리스트를 스트링 값으로 변환하여 출력합니다.
- 원래 영어로 출력했던걸 한글로 출력하는걸로 변경 있습니다
- 
-
> ✨ Feat: #45-Perfume 플라스크 연결 및 레시피 스트링으로 변경

- src/main/java/fouragrant/scentasy/biz/calendar/controller/MemoController.java
- src/main/java/fouragrant/scentasy/biz/calendar/domain/Memo.java
- src/main/java/fouragrant/scentasy/biz/calendar/dto/MemoDto.java
- src/main/java/fouragrant/scentasy/biz/calendar/repository/MemoRepository.java
- src/main/java/fouragrant/scentasy/biz/calendar/service/MemoService.java
- src/main/java/fouragrant/scentasy/biz/perfume/domain/Perfume.java
- src/main/java/fouragrant/scentasy/common/exception/ErrorCode.java
- src/main/resources/application.yml
관련 이슈
- calendar의 메모 관련 api 구현
- 메모 생성
- 메모 조회
- 메모 삭제
- 메모 리스트 조회
- 
- 
-
> ✨ Feat: #47-calendar 메모 관련 API

- src/main/java/fouragrant/scentasy/biz/calendar/controller/MemoController.java
관련 이슈
- 캘린더 기능 오류 수정(삭제 부분)
- 삭제 부분 구현에서 변수 잘못 작성한 부분을 수정하였습니다
- 삭제 부분 구현에서 변수 잘못 작성한 부분을 수정하였습니다
- 
-
> 🐛 Bug: #50-캘린더 기능 오류 수정

- src/main/java/fouragrant/scentasy/biz/calendar/controller/MemoController.java
- src/main/java/fouragrant/scentasy/biz/post/controller/CommentController.java
- src/main/java/fouragrant/scentasy/biz/post/controller/PostController.java
- src/main/resources/application.yml
관련 이슈
- swagger 오류 사항 수정
- post swagger 오류 사항 수정
- comment swagger 오류 사항 수정
- memo swagger 오류 사항 수정
- 
- 
-
> 🛠️ Refactor: #52- swagger 오류 사항 수정

- build.gradle
- src/main/java/fouragrant/scentasy/biz/member/cotroller/ExtraInfoController.java
- src/main/java/fouragrant/scentasy/biz/member/dto/ExtraInfoResDto.java
- src/main/java/fouragrant/scentasy/biz/member/repository/ExtraInfoRepository.java
- src/main/java/fouragrant/scentasy/biz/member/service/ExtraInfoService.java
- src/main/java/fouragrant/scentasy/biz/member/service/MemberService.java
- src/main/java/fouragrant/scentasy/biz/mypage/MypageController.java
- src/main/java/fouragrant/scentasy/biz/mypage/controller/MypageController.java
- src/main/java/fouragrant/scentasy/biz/mypage/controller/S3Controller.java
- src/main/java/fouragrant/scentasy/biz/mypage/service/S3Service.java
- src/main/java/fouragrant/scentasy/common/exception/ErrorCode.java
- src/main/java/fouragrant/scentasy/config/S3Config.java
- src/main/resources/application-dev.yml
- src/main/resources/application-local.yml
관련 이슈
- #36 
- 마이페이지에서 필요한 API를 구현했습니다.
주요 변경 사항이나 추가된 기능에 대해 설명해 주세요.
- 멤버 정보 조회 기능
- 멤버 추가정보 수정 기능
- S3 개발환경 세팅
- 멤버 프로필 사진 등록 기능
- 향기 사진 URL 조회 기능
변경된 코드를 테스트하는 방법을 설명해 주세요. 
- 스웨거 참고해 주세요!
> ✨ Feature: #36 마이페이지 관련 기능 구현

- src/main/java/fouragrant/scentasy/biz/perfume/controller/PerfumeController.java
관련 이슈
- #20 
- 스웨거 전체 향수 조회 API의 응답 데이터 형식을 수정하였습니다.
- Perfume -> Integer 변경
> ⚒️ Refactor: 멤버 전체 향수 개수 조회 스웨거 설정 수정

- src/main/java/fouragrant/scentasy/tcp/TcpTestController.java
관련 이슈
- #49 
- 라즈베리파이와 TCP 통신을 위한 테스트 코드를 구현합니다.
- RASPBERRYPI_IP 환경변수에 연결된 네트워크 IP 주소를 작성해주세요
> ✨ Feat: tcp 통신 테스트 구현

- src/main/java/fouragrant/scentasy/biz/perfume/controller/PerfumeDeviceController.java
- src/main/java/fouragrant/scentasy/biz/perfume/repository/PerfumeRepository.java
- src/main/java/fouragrant/scentasy/biz/perfume/service/PerfumeDeviceService.java
관련 이슈
- #61 
- tcp 통신을 통한 perfume 제작을 위한 기능을 구현했습니다.
- tcp 통신으로 perfume의 레시피 데이터를 기기로 전송합니다.
> ✨ Feature: tcp 통신을 통한 perfume 제작 기능 구현

- src/main/java/fouragrant/scentasy/biz/perfume/controller/PerfumeController.java
- src/main/java/fouragrant/scentasy/biz/perfume/domain/Accord.java
- src/main/java/fouragrant/scentasy/biz/perfume/domain/Perfume.java
- src/main/java/fouragrant/scentasy/biz/perfume/dto/FlaskResponse.java
- src/main/java/fouragrant/scentasy/biz/perfume/dto/PerfumeDto.java
- src/main/java/fouragrant/scentasy/biz/perfume/dto/PerfumeRecipeResDto.java
- src/main/java/fouragrant/scentasy/biz/perfume/service/PerfumeRecipeService.java
- src/main/java/fouragrant/scentasy/biz/perfume/service/PerfumeService.java
관련 이슈
- #35 
- 향수 정보를 플라스크와 연결하고 반환값을 변경했습니다.
- 플라스크 서버로부터 향수 어코드 예측값, 제목, 설명을 받아 저장합니다.
- 향수 정보 반환 시 어코드의 한글 이름과 영어 이름을 함께 반환합니다.
- 향수 레시피 생성 시 향수 ID, 제목, 설명, 노트, 어코드를 반환합니다.
> ✨ Feature: #35 향수 정보 플라스크 연결 및 반환값 변경

- src/main/java/fouragrant/scentasy/biz/perfume/dto/PerfumeDto.java
관련 이슈
- #35 
- 향수 DTO 향수 ID 추가
- 향수 정보 조회 시 향수 ID를 함께 반환합니다.
> 🛠️ refac: #35 향수 DTO 향수 ID 추가

- src/main/java/fouragrant/scentasy/biz/perfume/dto/PerfumeRecipeResDto.java
- src/main/java/fouragrant/scentasy/biz/perfume/service/PerfumeRecipeService.java
관련 이슈
- #45 
- 향수 레시피 DTO 향수 생성 날짜 추가
- 향수 레시피 생성 시 향수 생성 날짜를 함께 반환합니다.
> 🛠️ Refactor: 향수 레시피 DTO 향수 생성 날짜 추가

- src/main/java/fouragrant/scentasy/ScentasyApplication.java
- src/main/java/fouragrant/scentasy/biz/chat/controller/ChatController.java
- src/main/java/fouragrant/scentasy/biz/chat/service/ChatService.java
- src/main/java/fouragrant/scentasy/config/CorsConfig.java
- src/main/java/fouragrant/scentasy/config/SwaggerConfig.java
- src/main/resources/application.yml
관련 이슈
- #68 
- 채팅 세션 id의 형식 변경 chat_{int}_{nickname}에서 chat{int}의 형식으로 변경
- 스웨거 CORS 및 보안 스키마 수정 작업
- 채팅 세션 id의 형식이 변경되었습니다.
- 스웨거의 CORS 및 보안 스키마 수정 작업을 진행했습니다.
- 하드코딩된 서버 주소를 환경변수로 처리하도록 수정했습니다.
- 스웨거, 포스트맨,
- application.yml에서 환경변수로 처리하도록 작업했습니다! 풀 받고 주의해주세요!!
> 🔨 Refactor: 채팅 세션 id의 형식 변경 및 스웨거 수정 작업

- src/main/java/fouragrant/scentasy/biz/post/dto/PostResDto.java
- src/main/java/fouragrant/scentasy/biz/post/mapper/PostMapper.java
- src/main/java/fouragrant/scentasy/biz/post/repository/PostRepository.java
- src/main/java/fouragrant/scentasy/biz/post/service/PostService.java
- src/main/resources/application-local.yml
- src/main/resources/application.yml
관련 이슈
- 커뮤니티 조회시 포스트아이디 조회 수정합니다
- 
- 
- 
-
> 🔨 Refactor: 커뮤니티 조회 수정

- src/main/java/fouragrant/scentasy/biz/chat/repository/ChatRepository.java
- src/main/java/fouragrant/scentasy/biz/chat/service/ChatService.java
관련 이슈
- #73 
- 새로운 session Id 생성 호출 시 chat의 수를 count하여 생성하는 오류를 해결했습니다. 
- session Id에서 'chat1' 부분에서 정수 부분만 추출하여 +1하여 새로운 sessionId를 생성합니다.
- postman
> fix: new session id 생성 시 발생하는 오류 해결

- src/main/java/fouragrant/scentasy/biz/mypage/controller/MypageController.java
- src/main/java/fouragrant/scentasy/biz/perfume/dto/AccordStatisticsResDto.java
- src/main/java/fouragrant/scentasy/biz/perfume/repository/PerfumeRepository.java
- src/main/java/fouragrant/scentasy/biz/perfume/service/PerfumeService.java
- src/main/resources/application.yml
관련 이슈
- #72 
- 마이페이지에서 사용자 향수의 노트 값 통계를 get하는 API를 구현했습니다.
- 사용자 향수의 노트 값 통계를 get하는 기능이 추가 되었습니다
- 
-
> ✨ Feature: #72 mypage 노트 값 통계 구현
